name: copilot-deploy-frontend

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        required: true
        type: string
      DEPLOYMENT_NAME:
        required: true
        type: string
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true

permissions:
  contents: read

jobs:
  webapp:
    environment: ${{inputs.ENVIRONMENT}}
    permissions:
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - { dotnet: "6.0", configuration: Release, os: ubuntu-latest }

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          clean: true
          fetch-depth: 0

      - name: Install Azure CLI
        run: |
          sudo apt update && sudo apt-get install curl -y
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Install Keyring
        run: |
          sudo apt-get install gnome-keyring -y

      - name: "Install SWA CLI"
        run: npm install -g @azure/static-web-apps-cli

      - name: Azure login
        uses: azure/login@v1
        with:
          client-id: ${{secrets.AZURE_CLIENT_ID}}
          tenant-id: ${{secrets.AZURE_TENANT_ID}}
          subscription-id: ${{secrets.AZURE_SUBSCRIPTION_ID}}
          enable-AzPSSession: false

      - name: "Get and Mask SWA Deployment Token"
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            webappName=$(az deployment group show --name ${{inputs.DEPLOYMENT_NAME}} --resource-group ${{vars.CC_DEPLOYMENT_GROUP_NAME}} --output json | jq -r '.properties.outputs.webappName.value')
            swaToken=$(az staticwebapp secrets list --name "$webappName" --resource-group ${{vars.CC_DEPLOYMENT_GROUP_NAME}} --query "properties.apiKey" --output json | jq -r)
            echo "::add-mask::$swaToken"
            echo "SWA_CLI_DEPLOYMENT_TOKEN=$swaToken" >> $GITHUB_ENV

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: '5.x'

      - name: Determine version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0

      - name: Set version tag
        id: versiontag
        run: |
          VERSION_TAG="${{ steps.gitversion.outputs.Major }}."
          VERSION_TAG+="${{ steps.gitversion.outputs.Minor }}."
          VERSION_TAG+="${{ steps.gitversion.outputs.CommitsSinceVersionSource }}"
          echo $VERSION_TAG
          echo "versiontag=$VERSION_TAG" >> "$GITHUB_OUTPUT"

      - name: Deploy SWA
        run: |
          scripts/deploy/deploy-webapp.sh --subscription ${{secrets.AZURE_SUBSCRIPTION_ID}} --resource-group ${{vars.CC_DEPLOYMENT_GROUP_NAME}} --deployment-name ${{inputs.DEPLOYMENT_NAME}} --client-id ${{vars.FRONTEND_CLIENT_ID}} --no-redirect --version ${{ steps.versiontag.outputs.versiontag }} --version-info "Built from commit ${{ steps.gitversion.outputs.ShortSha }} on $(date +"%Y-%m-%d")"
